Add paging functionally
haruguchi-yuma/book_app pull request #2
Opened 2020-09-13 06:29 UTC by haruguchi-yuma

kaminariを使ってページング処理を実装しました。

2020-09-15 05:48 UTC, komagata requested changes

2020-09-15 05:48 UTC, komagata commented on app/controllers/books_controller.rb
> +    @books = Book.page(params[:page]).per(15)
マジックナンバーになっているのでkaminariの機能か定数にしたいですね。

[マジックナンバーが無いか - 初心者がRailsプロジェクトへの初PRする前に見るチェックリスト \- komagataのブログ](https://docs.komagata.org/5676#magic_number)

2020-09-22 09:34 UTC, haruguchi-yuma commented on app/controllers/books_controller.rb
> +    @books = Book.page(params[:page]).per(15)
15というのが後から見た人にわからないということですね。
マジックナンバー注意していなかったので、気づけませんでした。
設定ファイルを用意し、そこに記述しました！

2020-09-23 07:50 UTC, komagata requested changes

2020-09-23 07:50 UTC, komagata commented on config/locales/kaminari.ja.yml
> +        display_entries: "全%{total}件中 %{first}&nbsp;-&nbsp;%{last}件の%{entry_name}が表示されています"
最終行に改行がないようです〜

[ファイルの末尾に改行が無いか - 初心者がRailsプロジェクトへの初PRする前に見るチェックリスト \- komagataのブログ](https://docs.komagata.org/5676#crlf)

2020-09-23 15:12 UTC, haruguchi-yuma commented on config/locales/kaminari.ja.yml
> +        display_entries: "全%{total}件中 %{first}&nbsp;-&nbsp;%{last}件の%{entry_name}が表示されています"
rubocopを通したつもりだったのですが、設定ファイルを見ても最終行の改行をチェックする項目が見当たらなかったです。なので、エディタの設定で改行処理をしました。

2020-09-24 04:24 UTC, komagata approved these changes
確認しました、OKですー🙆‍♂️

2021-10-20 04:16 UTC, merged